### ISSUE TITLE
Unable to use DQL string_functions

### ISSUE THREAD

**Issue by NikoGrano** [RamyHakam/multi_tenancy_bundle#28]
Normally you can define `string_functions` in doctrine like this:

```yaml
doctrine:
    dbal:
        ...

    orm:
        ...
        mappings:
            App:
                ...

        dql:
            string_functions:
                DATE: DoctrineExtensions\Query\Mysql\Date
```

However this bundle does not port these defined `string_functions` to the `tenant` entity manager, nor is there any possible way to configure these to current bundle.

Would recommend make this configurable to the bundle configuration OR just copy the configuration from the doctrine bundle.

I did following later with linked patch.
