### ISSUE TITLE
Config default not changed

### ISSUE THREAD

**Issue by jbalatero** [RamyHakam/multi_tenancy_bundle#4]
These configs are not changed 
- `tenant_migration_namespace`
- `tenant_entity_manager.mapping.prefix`

Here's my config:
```
hakam_multi_tenancy:
  ...

  tenant_migration:
    tenant_migration_namespace: TenantMigrations
    tenant_migration_path: '%kernel.project_dir%/migrations/Tenant'
  tenant_entity_manager:
    mapping:
      type:   annotation
      dir:   '%kernel.project_dir%/src/Entity/Tenant'
      prefix: App\Entity\Tenant
      alias:   Tenant
```

When doing `bin/console debug:config doctrine`:

![image](https://user-images.githubusercontent.com/3615746/179896654-d452a7fd-1617-48fb-b9bd-12cfc9383dbd.png)
